# Edge Mental Health Agent Configuration

# Model settings
model:
  base_model: "internlm2/internlm2-7b"
  pt_checkpoint: "artifacts/pt"
  sft_checkpoint: "artifacts/sft"
  hf_export_dir: "artifacts/hf_export"
  max_new_tokens: 300
  temperature: 0.7
  top_p: 0.9

# Training settings
training:
  domain_pt:
    output_dir: "runs/pt"
    per_device_train_batch_size: 2
    gradient_accumulation_steps: 8
    learning_rate: 0.00002
    num_train_epochs: 1
    max_length: 2048
    bf16: true
    fp16: false
    logging_steps: 20
    save_steps: 500
    save_total_limit: 2
  
  sft:
    output_dir: "runs/sft"
    per_device_train_batch_size: 1
    gradient_accumulation_steps: 16
    learning_rate: 0.00001
    num_train_epochs: 2
    max_length: 2048
    bf16: true
    evaluation_strategy: "steps"
    eval_steps: 500
    logging_steps: 50
    save_steps: 500

# Data paths
data:
  raw_dir: "data/raw"
  processed_dir: "data/processed"
  domain_corpus: "data/processed/domain_corpus.jsonl"
  sft_train: "data/processed/sft.jsonl"
  sft_val: "data/processed/val.jsonl"

# Sensor encoding settings
sensor:
  window_days: 14
  ranges:
    sleep_efficiency: [0.7, 0.9]
    avg_sleep_duration_h: [5.5, 8.5]
    steps: [2000, 10000]
    screen_time_min: [60, 240]
    unlocks: [30, 120]

# Counterfactual augmentation
augmentation:
  perturbation_probability: 0.6
  noise_ranges:
    sleep_efficiency: [-0.2, 0.2]
    screen_time_multiplier: [0.5, 1.8]
    ema_mood_range: [-1, 1]
    missing_probability: 0.2

# Quantization settings  
quantization:
  preset: "q4f16_1"
  mlc_output_dir: "mobile/mlc-models"
  targets: ["android", "ios"]

# Safety settings
safety:
  emergency_keywords: ["hurt myself", "kill myself", "end it all", "suicide", "harm others"]
  emergency_helplines:
    us: "988 (Suicide & Crisis Lifeline)"
    uk: "116 123 (Samaritans)"
    international: "befrienders.org"
  
# Logging
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/agent.log"

# Development settings
dev:
  debug: false
  mock_model_responses: false
  test_data_size: 100